# Audio service configuration

# OSC (SuperCollider communication)
#[osc]
#host = "localhost"
#send_port = 5570             # Port for sending OSC messages to SuperCollider
#recv_port = 5571             # Port for receiving OSC messages from SuperCollider

# SuperCollider control
[supercollider]
auto_start = true            # Automatically start SuperCollider on service launch
sclang_path = "sclang"       # Path to SuperCollider language interpreter
script_path = "experimance_audio.scd"  # Path to SuperCollider script (leave null to auto-discover)
startup_timeout = 10.0       # Seconds to wait for SuperCollider startup
log_dir = "services/audio/logs"  # Directory where SuperCollider log files are written
output_channels=6            # 5.1 surround: L, R, C, LFE, LS, RS
input_channels=2
device="ICUSBAUDIO7D"        # USB audio interface (will resolve to hw:X,Y automatically)

# JACK configuration
auto_start_jack = true       # Automatically start JACK if not running
jack_sample_rate = 48000     # JACK sample rate
jack_buffer_size = 1024      # JACK buffer size (frames per period)
jack_periods = 2             # Number of periods in JACK buffer
jack_output_channels = 6     # Match device capability (5.1 surround)

enable_surround=true
environment_channels=[0,1]
sfx_channels=[0,1]
music_channels=[4,5]

# Audio playback settings
[audio]
master_volume = 0.2          # Master volume level (0.0 to 1.0)
environment_volume = 0.3     # Environment sounds volume level
music_volume = 0.5           # Music loops volume level
sfx_volume = 0.3             # Sound effects volume level
config_dir = "services/audio/config"  # Directory containing JSON audio configs
