# Sohkepayin Core Service Configuration

service_name = "sohkepayin_core"

[panorama]
# Base panorama dimensions (before mirroring)
display_width = 5760
display_height = 1080
generated_width = 2240  # 3 tiles
generated_height = 420

[tiles]
# Tile generation settings
display_width = 1920
display_height = 1080
generated_width = 1344
generated_height = 758
min_overlap_percent = 0
max_megapixels = 1.1  # Keep tiles around 1MP for reasonable generation time

[llm]
# LLM provider configuration
provider = "openai"
model = "gpt-4o"
max_tokens = 500
temperature = 0.7
timeout = 30.0
system_prompt_or_file = "system_prompt_t2i_prompt.md"

[rendering]
# Image generation timeouts
timeout = 120.0
base_image_timeout = 60.0
tile_timeout = 90.0
