DEEP_THOUGHTS = {
    "wilderness": {
        "rainforest": "Even without you, the rainforest sings. Perhaps louder.",
        "temperate_forest": "Every tree is a silent witness, keeping secrets older than civilization.",
        "boreal_forest": "Cold roots dreaming patiently beneath endless pine.",
        "deciduous_forest": "Leaves fall, indifferent to the absence of applause.",
        "desert": "Empty sands still whisper stories. Who listens now?",
        "mountain": "Mountains rise and erode, patiently waiting for witnesses.",
        "tropical_island": "Paradise never missed humanity; it only missed being named.",
        "river": "Rivers carved valleys long before your first footprint.",
        "tundra": "Even in emptiness, the tundra waits. Quietly, endlessly.",
        "steppe": "Grass sways gently, unconcerned by the lack of eyes watching.",
        "coastal": "The tides keep perfect time, indifferent to human clocks.",
        "swamp": "Life bubbles beneath the mud, perfectly content without a witness.",
        "plains": "Endless horizons never required your gaze to feel vast.",
        "arctic": "Ice speaks in cracks and groans; no ears required.",
        "jungle": "Hidden paths through dense green, waiting for footsteps never taken.",
    },
    "pre_industrial": {
        "rainforest": "A village quietly breathing within a living cathedral.",
        "temperate_forest": "Logs piled for winter speak quietly of survival.",
        "boreal_forest": "Small fires in vast darkness, a warm defiance.",
        "deciduous_forest": "Paths marked softly, whispers of careful coexistence.",
        "desert": "Water here is hope itself, measured by careful hands.",
        "mountain": "Terraced slopes: labor etched in stone, harmony in hardship.",
        "tropical_island": "Canoes bob gently, tethered dreams of distant shores.",
        "river": "A village shaped by the current, humble in its acceptance.",
        "tundra": "Warmth is always borrowed in this frozen place.",
        "steppe": "Nomads passing quietly, leaving only memories in grass.",
        "coastal": "Fishing nets cast rhythms upon the waves, patiently waiting.",
        "swamp": "Settlements on stilts, lives balanced carefully above dark waters.",
        "plains": "Villages like islands in seas of grass, waves gently parting.",
        "arctic": "Igloos breathe softly beneath dancing northern lights.",
        "jungle": "Villages hidden by leaves, sheltered from history's gaze.",
    },
    "early_industrial": {
        "rainforest": "Iron begins its intrusion, paths cutting deeper than shadows.",
        "temperate_forest": "Smoke rising softly, industry weaving into the woods.",
        "boreal_forest": "Machines hum quietly, reshaping forests into commodities.",
        "deciduous_forest": "Wood feeds industry's appetite, yet forests endure—for now.",
        "desert": "Tracks across sands, marking human determination and folly.",
        "mountain": "Iron rails stitched mountainsides, binding nature to commerce.",
        "tropical_island": "Ships bring whispers of distant smoke and change.",
        "river": "Mill wheels turn gently, unaware of their own significance.",
        "tundra": "Ice begins to feel footsteps more frequent, less cautious.",
        "steppe": "Steam whispers promise; grasslands listen uncertainly.",
        "coastal": "Ports fill with ambition, horizons no longer endless.",
        "swamp": "Dredging canals carve hope and scars in equal measure.",
        "plains": "Tracks mark quiet conquest of grasses now divided.",
        "arctic": "Whaling ships appear: ice meets iron for the first time.",
        "jungle": "Rubber trails stretch like veins, feeding distant industry.",
    },
    "late_industrial": {
        "rainforest": "Machinery's chorus drowns ancient voices under canopies.",
        "temperate_forest": "Felled trees echo a progress that begins to ache.",
        "boreal_forest": "Rail lines cut deeper; forests yield their solitude.",
        "deciduous_forest": "Cities bloom as trees vanish, concrete roots take hold.",
        "desert": "Mining scars begin to replace mirages with reality.",
        "mountain": "Tunnels and rails consume mountains slowly, certainly.",
        "tropical_island": "Plantations reshape paradise, beauty bending under burden.",
        "river": "Waterways churn under wheels of endless ambition.",
        "tundra": "Footprints deepen; ice meets steel reluctantly.",
        "steppe": "Grasslands fenced, freedoms quietly ending.",
        "coastal": "Steamships now dominate shores once free of smoke.",
        "swamp": "Machines drain life slowly, replacing it with ‘progress'.",
        "plains": "Steam plows churn fields once calm under the sky.",
        "arctic": "Ice gives way to metal hulls, reluctant acceptance.",
        "jungle": "Extraction leaves wounds, invisible until they're irreversible.",
    },
    "modern": {
        "rainforest": "Roads slice deep, scars now undeniable beneath green.",
        "temperate_forest": "Highways whisper where birds once sang clearly.",
        "boreal_forest": "Industry's hum now constant; silence a fading memory.",
        "deciduous_forest": "Suburbs claim forests inch by inch, unnoticed sacrifices.",
        "desert": "Concrete blooms in sand, mirroring humanity's illusions.",
        "mountain": "Tourist postcards replace mountaintops with souvenirs.",
        "tropical_island": "Airfields interrupt horizons; beauty now packaged.",
        "river": "Dams halt rivers, harnessing freedom for electricity.",
        "tundra": "Radio signals crackle, silence finally broken.",
        "steppe": "Machines replace hooves, speed overtaking quiet.",
        "coastal": "Boardwalks claim beaches, ocean now spectacle.",
        "swamp": "Mosquitoes yield slowly to concrete, life replaced.",
        "plains": "Agriculture becomes industry, sky no longer limitless.",
        "arctic": "Stations dot ice, human curiosity etched permanently.",
        "jungle": "Bulldozers erase quietly, systematically, forever.",
    },
    "current": {
        "rainforest": "Chainsaws now sing louder than birds.",
        "temperate_forest": "Forests now ornamental; suburbs sprawl quietly onward.",
        "boreal_forest": "Log trucks carve silent futures through lingering trees.",
        "deciduous_forest": "Parks confined by highways—nature neatly boxed.",
        "desert": "Solar panels bloom, mirroring new dreams and old sins.",
        "mountain": "Instagram summits replace solitude with spectacle.",
        "tropical_island": "Resorts rise—beauty repackaged, reality filtered.",
        "river": "Concrete banks tame waters no longer free.",
        "tundra": "Drill rigs punctuate horizon; stillness broken irrevocably.",
        "steppe": "Tractors roam empty spaces, solitude mechanized.",
        "coastal": "Cities climb skyward; waves quietly recede.",
        "swamp": "Highways float above waters—wildness bypassed, unnoticed.",
        "plains": "Monoculture stretches endlessly beneath drone shadows.",
        "arctic": "Ice shrinks silently; whispers of warnings ignored.",
        "jungle": "Palm oil roads carve quiet catastrophe through green.",
    },
    "dystopia": {
        "rainforest": "Smoke now competes with clouds; lungs of the planet choking on ash.",
        "temperate_forest": "Forests wither under acid rains; the soil remembers your mistakes.",
        "boreal_forest": "Endless winter shadows broken only by machines fighting over dying resources.",
        "deciduous_forest": "Leaves refuse to return, sensing the poisoned air.",
        "desert": "The sands expand tirelessly, burying cities and secrets alike.",
        "mountain": "Avalanches reclaim your fortresses; gravity correcting arrogance.",
        "tropical_island": "Paradise drowned beneath waves swollen with your neglect.",
        "river": "Rivers no longer flow; stagnant water reflects skies blackened by war.",
        "tundra": "Permafrost melted into mud; cold refuge turned endless mire.",
        "steppe": "Grass scorched into dust; hunger wandering endlessly.",
        "coastal": "Storms rage, swallowing coasts abandoned by hope.",
        "swamp": "Toxic waters bubble, reclaiming land too poisoned for life.",
        "plains": "Winds howl across cracked soil, whispering famine's name.",
        "arctic": "Ice retreats mournfully, unable to cool your burning legacy.",
        "jungle": "Humidity thick with disease; vibrant greens replaced by rot."
    },
     "future": {
        "rainforest": "Sensors bloom like orchids, guarding harmony beneath every leaf.",
        "temperate_forest": "Networks root deeply alongside trees, quietly protecting balance.",
        "boreal_forest": "Machines whisper softly to pines, their dialogue ancient yet new.",
        "deciduous_forest": "Robotic caretakers tend gently to branches, sharing mutual shelter.",
        "desert": "Solar arrays gleam peacefully, partners with sand and sunlight.",
        "mountain": "Artificial eyes watch carefully from peaks, forever vigilant guardians.",
        "tropical_island": "Paradise now shared, digital beings learning gentleness from waves.",
        "river": "Water monitored but flowing free, humanity guided by wise machines.",
        "tundra": "Machines softly warm permafrost villages, careful stewards of the cold.",
        "steppe": "Robotic shepherds roam grasslands, protecting balance from greed.",
        "coastal": "Ocean and city speak in harmony, technology mediating tides of peace.",
        "swamp": "Bio-sensors quietly pulse beneath still waters, preserving fragile life.",
        "plains": "AI watches gently from towers, ensuring wheat ripens without conflict.",
        "arctic": "Drones dance gracefully under auroras, eternal watch against exploitation.",
        "jungle": "Humans and machines coexist under canopy shade, carefully protecting their mutual home."
    },
    "ruins": {
        "rainforest": "Vines tenderly embrace fallen skyscrapers, erasing your skyline.",
        "temperate_forest": "Roots patiently crack asphalt, undoing what hands built.",
        "boreal_forest": "Trees quietly sprout within rusted machinery, indifferent to purpose.",
        "deciduous_forest": "Leaves dance again in broken streets, celebrating solitude reclaimed.",
        "desert": "Dunes smooth over crumbling foundations, gently covering your mistakes.",
        "mountain": "Mountains breathe deeply again, freed from human ambition.",
        "tropical_island": "Beaches reappear untouched; paradise quietly returns.",
        "river": "Water flows freely again, carving new stories through empty cities.",
        "tundra": "Cold silence returns, ice hiding what once was.",
        "steppe": "Grasses ripple in the wind, quietly erasing scars from war.",
        "coastal": "Waves reclaim shores, healing the wounds of civilization.",
        "swamp": "Life slowly thrives again, oblivious to rusted bridges and abandoned roads.",
        "plains": "Wildflowers bloom, turning former battlegrounds into gentle memorials.",
        "arctic": "Ice grows quietly over abandoned structures, forgiving slowly.",
        "jungle": "Green swallows remnants of buildings, softly burying your ambitions."
    }
}