name = "Face Detection"
description = "Optimized for face detection with motion, ideal for seated audiences"
environment = "indoor"
lighting = "mixed"

[hog]
win_stride_x = 8
win_stride_y = 8
padding_x = 4
padding_y = 4
scale = 1.05
hit_threshold = 0.0
group_threshold = 2

[mog2]
detect_shadows = true
var_threshold = 40.0
history = 250

[detection]
detection_scale_factor = 0.8
min_person_height = 50
motion_threshold = 800
motion_intensity_threshold = 0.008
detection_history_size = 5
stability_threshold = 0.5
enable_hog_detection = false
enable_face_detection = true
enable_motion_detection = true

[face]
model_path = "models/face_detection_yunet_2023mar.onnx"
input_size = [
    320,
    320,
]
score_threshold = 0.5
nms_threshold = 0.3
top_k = 5000
min_face_size = 20

[confidence]
person_base_confidence = 0.0
person_count_weight = 0.2
person_weight_factor = 0.4
motion_confidence_weight = 0.4
motion_only_threshold = 0.3
motion_only_confidence_factor = 0.7
max_combined_confidence = 0.95
absence_confidence = 0.9
