name = "Gallery Dim"
description = "Optimized for gallery/museum with dim, controlled lighting"
environment = "indoor"
lighting = "dim"

[hog]
win_stride_x = 8
win_stride_y = 8
padding_x = 4
padding_y = 4
scale = 1.03
hit_threshold = -0.2
group_threshold = 2

[mog2]
detect_shadows = true
var_threshold = 30.0
history = 500

[detection]
detection_scale_factor = 0.6
min_person_height = 50
motion_threshold = 600
motion_intensity_threshold = 0.005
detection_history_size = 5
stability_threshold = 0.6

[confidence]
person_base_confidence = 0.3
person_count_weight = 0.2
person_weight_factor = 0.4
motion_confidence_weight = 0.3
motion_only_threshold = 0.4
motion_only_confidence_factor = 0.6
max_combined_confidence = 0.95
absence_confidence = 0.9

[camera]
name = "Gallery Dim Lighting"
description = "Camera settings optimized for dim gallery/museum lighting"
environment = "gallery"
auto_apply = true

[camera.settings]
# Format settings - MJPG for better low light performance
preferred_format = "MJPG"
preferred_width = 1280
preferred_height = 720
preferred_fps = 30

# Exposure settings for low light
auto_exposure = 3  # Aperture Priority Mode for low light
exposure_dynamic_framerate = 1  # Allow frame rate to drop for longer exposure

# Lighting compensation for dim environment
backlight_compensation = 70  # Higher compensation for uneven lighting
gain = 25  # Higher gain for sensitivity in dim light

# White balance for gallery lighting
white_balance_automatic = 1  # Auto white balance
white_balance_temperature = 4000  # Warmer for gallery lighting

# Image quality optimized for dim light detection
brightness = 15  # Brighter for dim environments
contrast = 45  # Higher contrast for better edge detection
saturation = 40  # Lower saturation to reduce noise
sharpness = 4  # Higher sharpness for detection
gamma = 125  # Adjusted gamma for better dynamic range

# Power line frequency (adjust for your region)
power_line_frequency = 2  # 60 Hz (use 1 for 50 Hz in Europe)
