name = "Indoor Office"
description = "Optimized for indoor office/studio environments with stable lighting"
environment = "indoor"
lighting = "bright"

[hog]
win_stride_x = 8
win_stride_y = 8
padding_x = 4
padding_y = 4
scale = 1.05
hit_threshold = 0.0
group_threshold = 2

[mog2]
detect_shadows = true
var_threshold = 40.0
history = 400

[detection]
detection_scale_factor = 0.5
min_person_height = 60
motion_threshold = 800
motion_intensity_threshold = 0.008
detection_history_size = 5
stability_threshold = 0.7

[face]
model_path = "models/face_detection_yunet_2023mar.onnx"
input_size = [
    320,
    320,
]
score_threshold = 0.5
nms_threshold = 0.3
top_k = 5000
min_face_size = 20

[confidence]
person_base_confidence = 0.3
person_count_weight = 0.2
person_weight_factor = 0.4
motion_confidence_weight = 0.3
motion_only_threshold = 0.4
motion_only_confidence_factor = 0.6
max_combined_confidence = 0.95
absence_confidence = 0.9

[camera]
name = "Indoor Office"
description = "Camera settings optimized for stable indoor office/studio lighting"
environment = "office"
auto_apply = true

[camera.settings]
# Format settings - balanced performance
preferred_format = "YUYV"
preferred_width = 640
preferred_height = 480
preferred_fps = 30

# Exposure settings for stable lighting
auto_exposure = 3  # Aperture Priority Mode
exposure_dynamic_framerate = 0  # Fixed frame rate in stable lighting

# Lighting compensation for office environment
backlight_compensation = 30  # Moderate compensation for office lighting
gain = 10  # Lower gain in bright environment

# White balance for office lighting
white_balance_automatic = 1  # Auto white balance
white_balance_temperature = 3200  # Cool office fluorescent lighting

# Image quality optimized for office detection
brightness = 0  # Neutral brightness in bright environment
contrast = 30  # Standard contrast
saturation = 50  # Standard saturation
sharpness = 2  # Moderate sharpness
gamma = 100  # Standard gamma

# Power line frequency (adjust for your region)
power_line_frequency = 2  # 60 Hz (use 1 for 50 Hz in Europe)
