name = "Outdoor Bright"
description = "Optimized for outdoor or very bright environments"
environment = "outdoor"
lighting = "bright"

[hog]
win_stride_x = 6
win_stride_y = 6
padding_x = 4
padding_y = 4
scale = 1.05
hit_threshold = 0.2
group_threshold = 2

[mog2]
detect_shadows = true
var_threshold = 60.0
history = 200

[detection]
detection_scale_factor = 0.4
min_person_height = 80
motion_threshold = 1500
motion_intensity_threshold = 0.015
detection_history_size = 5
stability_threshold = 0.8

[confidence]
person_base_confidence = 0.3
person_count_weight = 0.2
person_weight_factor = 0.4
motion_confidence_weight = 0.3
motion_only_threshold = 0.4
motion_only_confidence_factor = 0.6
max_combined_confidence = 0.95
absence_confidence = 0.9
