name = "Workshop Cluttered"
description = "Optimized for cluttered environments with variable lighting"
environment = "indoor"
lighting = "mixed"

[hog]
win_stride_x = 8
win_stride_y = 8
padding_x = 4
padding_y = 4
scale = 1.05
hit_threshold = 0.0
group_threshold = 2

[mog2]
detect_shadows = true
var_threshold = 45.0
history = 350

[detection]
detection_scale_factor = 0.7
min_person_height = 70
motion_threshold = 1200
motion_intensity_threshold = 0.012
detection_history_size = 7
stability_threshold = 0.8

[confidence]
person_base_confidence = 0.3
person_count_weight = 0.2
person_weight_factor = 0.4
motion_confidence_weight = 0.3
motion_only_threshold = 0.5
motion_only_confidence_factor = 0.6
max_combined_confidence = 0.95
absence_confidence = 0.9
