## Experimance Core Service Configuration

# Debugging and visualization options
visualize = false            # enable visual debugging - display depth image and processing flags

[experimance_core]
name = "experimance_core_dev"
heartbeat_interval = 3.0

[state_machine]
idle_timeout = 45.0          # seconds
wilderness_reset = 300.0     # seconds to full reset
interaction_threshold = 0.3  # threshold for user interaction detection
era_min_duration = 10.0      # minimum time in seconds before era can change

[camera]
# Core camera settings
resolution = [1280, 720]     # depth camera resolution (width, height)
fps = 30                    # camera frames per second 
min_depth = 0.46            # minimum depth value in meters
max_depth = 0.52            # maximum depth value in meters
align_frames = true         # use color frames to help align the depth frames
#json_config_path = "depth_camera_config_v2.json"  # path to RealSense JSON config

# Processing parameters
output_resolution = [1024, 1024]  # processed output size (width, height)
change_threshold = 50       # threshold for depth change detection
detect_hands = true         # enable hand detection
crop_to_content = true      # crop output to content area
warm_up_frames = 10         # number of frames to skip during warmup
lightweight_mode = false   # skip some processing for higher FPS
verbose_performance = true # show detailed performance timing
debug_mode = false          # include intermediate images for visualization

# Mask stability and bowl detection
mask_stability_frames = 20      # frames to analyze for mask stability
mask_stability_threshold = 0.95 # similarity threshold for mask stability (0.0-1.0)
mask_lock_after_stable = true   # lock mask once it becomes stable
mask_allow_updates = false      # allow mask updates when bowl moves significantly
mask_update_threshold = 0.7     # threshold for detecting bowl movement (0.0-1.0)

# Retry parameters
max_retries = 3             # maximum camera initialization retries
retry_delay = 2.0           # initial retry delay in seconds
max_retry_delay = 30.0      # maximum retry delay in seconds
aggressive_reset = false    # use more aggressive reset strategies
skip_advanced_config = false # skip advanced JSON config loading

# RealSense filters (manual control instead of JSON config)
# https://dev.intelrealsense.com/docs/post-processing-filters
enable_filters = true       # enable/disable post-processing filters
spatial_filter = true      # spatial edge-preserving filter
temporal_filter = true     # temporal filter to reduce temporal noise
decimation_filter = false  # decimation filter to reduce resolution
hole_filling_filter = false # hole filling filter
threshold_filter = false   # threshold filter for depth range

# Spatial filter settings
# Magnitute: Number of filter iterations
# Spatial filter smooths the image by calculating frame with alpha and delta settings. 
# Alpha defines the weight of the current pixel for smoothing, and is bounded within [25..100]%. 
# Delta defines the depth gradient below which the smoothing will occur as number of depth levels.
# An in-place heuristic symmetric hole-filling mode applied horizontally during the filter passes. 
# Intended to rectify minor artefacts with minimal performance impact
spatial_filter_magnitude = 2.0      # filter magnitude (1-5)
spatial_filter_alpha = 0.5          # alpha factor (0-1)
spatial_filter_delta = 20.0         # delta threshold (1-50)
spatial_filter_hole_fill = 1        # hole fill mode (0-5)

# Temporal filter settings
# The Alpha factor in an exponential moving average with Alpha=1 - no filter . Alpha = 0 - infinite filter
# Step-size boundary. Establishes the threshold used to preserve surfaces (edges)
# Persistence: A set of predefined rules (masks) that govern when missing pixels will be 
# replace with the last valid value so that the data will remain persistent over time:
#   Disabled - Persistency filter is not activated and no hole filling occurs.
#   Valid in 8/8 - Persistency activated if the pixel was valid in 8 out of the last 8 frames
#   Valid in 2/last 3 - Activated if the pixel was valid in two out of the last 3 frames
#   Valid in 2/last 4 - Activated if the pixel was valid in two out of the last 4 frames
#   Valid in 2/8 - Activated if the pixel was valid in two out of the last 8 frames
#   Valid in 1/last 2 - Activated if the pixel was valid in one of the last two frames
#   Valid in 1/last 5 - Activated if the pixel was valid in one out of the last 5 frames
#   Valid in 1/last 8 - Activated if the pixel was valid in one out of the last 8 frames
#   Persist Indefinitely - Persistency will be imposed regardless of the stored history (most aggressive filtering)
temporal_filter_alpha = 0.4         # alpha factor (0-1)
temporal_filter_delta = 20.0        # delta threshold (1-100)
temporal_filter_persistence = 3     # persistence control (0-8)

# Decimation filter settings
decimation_filter_magnitude = 2     # decimation factor (2-8)

# Hole filling filter settings
hole_filling_mode = 1               # hole filling mode (0=disabled, 1=fill_from_left, 2=farthest_from_around)

# Threshold filter settings
threshold_filter_min = 0.15         # minimum distance in meters
threshold_filter_max = 4.0          # maximum distance in meters

[audio]
tag_config_path = "config/audio_tags.json"  # path to audio tag configuration
interaction_sound_duration = 2.0            # duration for interaction sounds

[prompting]
data_path = "data/"                    # path to prompt data directory
locations_file = "locations.json"     # locations data file
developments_file = "anthropocene.json"  # developments data file
