## Experimance Core Service Configuration

[experimance_core]
name = "experimance_core_dev"
heartbeat_interval = 3.0

[state_machine]
idle_timeout = 45.0          # seconds
wilderness_reset = 300.0     # seconds to full reset
interaction_threshold = 0.3  # threshold for user interaction detection
era_min_duration = 10.0      # minimum time in seconds before era can change

[depth_processing]
camera_config_path = "services/core/depth_camera_config_high_accuracy.json"
resolution = [640, 480]     # depth camera resolution (10Hz max for this res)
fps = 30                    # camera frames per second 
change_threshold = 50       # threshold for depth change detection
min_depth = 0.49            # minimum depth value
max_depth = 0.56            # maximum depth value
output_size = [1024, 1024]  # processed output size

[audio]
tag_config_path = "config/audio_tags.json"  # path to audio tag configuration
interaction_sound_duration = 2.0            # duration for interaction sounds

[prompting]
data_path = "data/"                    # path to prompt data directory
locations_file = "locations.json"     # locations data file
developments_file = "anthropocene.json"  # developments data file
