## Image server configuration

# General settings
cache_dir = "images"         # Directory to cache generated images
max_cache_size_gb = 2.0      # Maximum size of image cache in GB

# ZeroMQ configuration
[zmq]
events_sub_address = "tcp://localhost:5555"  # Address to subscribe to events on
images_pub_address = "tcp://*:5558"         # Address to publish images on

# Generator configuration
[generator]
default_strategy = "fal"     # Options: "fal", "openai", "local", "mock"
timeout_seconds = 10         # Timeout for image generation requests

# FAL.AI configuration
[fal]
model_url = "fal.ai/sdxl-lightning"
dimensions = [1024, 1024]
num_inference_steps = 4

# OpenAI configuration (DALLE)
[openai]
model = "dall-e-3"
dimensions = [1024, 1024]
quality = "standard"

# Local SDXL configuration
[local]
model_path = "models/sdxl-base"
device = "cuda"
dimensions = [1024, 1024]
num_inference_steps = 30
