## Image server configuration

# General settings
cache_dir = "images"         # Directory to cache generated images
max_cache_size_gb = 2.0      # Maximum size of image cache in GB

# ZeroMQ configuration
#[zmq]

# Generator configuration
[generator]
default_strategy = "falai"     # Options: "falai", "openai", "sdxl", "mock"

# FAL.AI configuration
[falai]
#endpoint = "comfy/RKelln/experimance_hyper_depth_v5"
endpoint = "comfy/RKelln/experimancexilightningdepth"
model_url = "https://civitai.com/api/download/models/471120?type=Model&format=SafeTensor&size=full&fp=fp16"
lora_url = "https://civitai.com/api/download/models/152309?type=Model&format=SafeTensor"
lora_strength = 0.8
timeout = 90

# OpenAI configuration (DALLE)
[openai]
model = "dall-e-3"
dimensions = [1024, 1024]
quality = "standard"

# Local SDXL configuration  
[sdxl]
model_path = "models/sdxl-base"
device = "cuda"
dimensions = [1024, 1024]
num_inference_steps = 30

# Fake image generator
[mock]
#strategy: Literal["mock"] = "mock"
#image_size: tuple = (1024, 1024)
#background_color: tuple = (100, 150, 200)
#text_color: tuple = (255, 255, 255)
use_existing_images = true
existing_images_dir = "media/images/generated"