## Image server configuration

# General settings
cache_dir = "images"         # Directory to cache generated images
max_cache_size_gb = 2.0      # Maximum size of image cache in GB

# ZeroMQ configuration
#[zmq]
#image_request_pub = "tcp://localhost:5555"  # Address to subscribe to events on
#images_pub_address = "tcp://*:5558"         # Address to publish images on

# Generator configuration
[generator]
default_strategy = "mock"     # Options: "fal", "openai", "local", "mock"

# FAL.AI configuration
[falai]
endpoint = "comfy/RKelln/experimance_hyper_depth_v5"
model_url = "https://civitai.com/api/download/models/471120?type=Model&format=SafeTensor&size=full&fp=fp16"
lora_url = "https://civitai.com/api/download/models/152309?type=Model&format=SafeTensor"
lora_strength = 0.8

# OpenAI configuration (DALLE)
[openai]
model = "dall-e-3"
dimensions = [1024, 1024]
quality = "standard"

# Local SDXL configuration
[local]
model_path = "models/sdxl-base"
device = "cuda"
dimensions = [1024, 1024]
num_inference_steps = 30
